esphome:
  name: espidf

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: /github/workspace/components

uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

samsung_ac:
  debug_mqtt_host: 192.168.1.100
  debug_mqtt_port: 1883
  debug_mqtt_username: mqtt_user
  debug_mqtt_password: mqtt_pass

  debug_log_messages: false
  debug_log_messages_raw: false

  devices:
    - address: "20.00.00"
      climate:
        name: "Test"
      room_temperature:
        name: Test1_temp
      target_temperature:
        name: Test1_target
      power:
        name: Test1_power
