## BASIC CONFIGURATION
esphome:
  name: esphome-web-fd4e7c
  friendly_name: samsung_heatpump
  comment: "Samsung AC Heatpump"
  min_version: 2024.11.0
  name_add_mac_suffix: false

# Select chipset and board configuration - in this case M5STACK
esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

# [Optional] - Create web interface where you can control the AC from your web browser (without Home Assistant)
web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:
  platform: esphome

# Setup your WiFi password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Add this if not present:
  manual_ip:
    static_ip: 192.168.1.234
    gateway: 192.168.1.1
    subnet: 255.255.255.0

captive_portal:

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  id: uart_bus
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: "github://carltonlane79/esphome_samsung_hvac_bus@eu_heatpump"
#  - source: ./components  # Point to the components directory
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:
  id: samsung_ac_controller
  uart_id: uart_bus
  debug_mqtt_host: ""
  debug_mqtt_port: 1883
  debug_mqtt_username: ""
  debug_mqtt_password: ""
  
  # When enabled (set to true), this option will log the messages associated with undefined codes on the device. This is useful for debugging and identifying any unexpected or unknown codes that the device may receive during operation.
  debug_log_undefined_messages: true
  
  # When enabled (set to true), this option logs messages associated with defined codes on the device. This helps in monitoring the behavior of the device by recording the activity related to known, expected codes.
  debug_log_messages: true

  # Capabilities configure the features that all devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per-device basis (look below for that).
  capabilities: 
    vertical_swing: false
    horizontal_swing: false

  devices:
    - address: "20.00.00" # Indoor device address 
      capabilities:
        horizontal_swing: false
        vertical_swing: false

      climate:
        name: "Heat Pump climate (4001)"
        id: climate_20_00_00

      room_temperature:
        name: "Indoor Temperature (4203)"
        id: room_temperature_20_00_00
        accuracy_decimals: 1

      target_temperature:
        name: "Heat Pump target temperature (4201)"
        id: target_temperature_20_00_00

      power:
        name: "Heat Pump power (4000)"
        id: power_20_00_00

      mode:
        name: "Heat Pump mode (4001)"
        id: mode_20_00_00

      operation_mode:
        name: "Operation Mode (4001)"
        id: operation_mode_20_00_00
        message: 0x4001

      indoor_eva_in_temperature:
        name: "Evaporator Inlet Water Temperature (4205)"
        id: evap_inlet_water_temperature_20_00_00
        accuracy_decimals: 1
        #message: 0x4205

      indoor_eva_out_temperature:
        name: "Evaporator Outlet Water Temperature (4206)"
        id: evap_outlet_water_temperature_20_00_00
        accuracy_decimals: 1
        #message: 0x4206

      water_temperature:
        name: "Water Temperature (Heating Loop) (4236)"
        id: water_temperature_20_00_00
        accuracy_decimals: 1
        message: 0x4236

      # Indoor Custom sensors
      custom_sensor:

        - name: "Water Outlet Target Temperature (4247)"
          message: 0x4247
          id: water_outlet_target_temperature_20_00_00
          unit_of_measurement: "°C"
          accuracy_decimals: 1
          filters:
            - multiply: 0.1

        - name: "DHW Operation Enable (4065)"
          message: 0x4065
          id: dhw_operation_enable

        - name: "DHW Mode Setting (4066)"
          message: 0x4066
          id: dhw_mode_setting

        - name: "DHW Target Temperature (4235)"
          message: 0x4235
          unit_of_measurement: "°C"
          accuracy_decimals: 1
          filters:
            - multiply: 0.1
          id: dhw_setpoint_temp

        - name: "Backup Heater Status (406C)"
          message: 0x406C
          id: dhw_backup_heater_status

        - name: "Booster Heater Status (4087)"
          message: 0x4087
          id: dhw_booster_heater_status

        - name: "3-Way Valve Position (4067)"
          message: 0x4067
          id: dhw_three_way_valve_position

        - name: "Circulation Pump Speed (40C4)"
          message: 0x40C4
          unit_of_measurement: "%"
          id: dhw_circulation_pump_speed

        - name: "Water Flow Rate (4238)"
          message: 0x4238
          unit_of_measurement: "L/min"
          id: dhw_water_flow_rate

        - name: "Water Pressure (hPa) (4239)"
          message: 0x4239
          unit_of_measurement: "hPa"
          id: dhw_water_pressure

        - name: "Heat Pump Operation Mode (8001)"
          message: 0x8001
          id: dhw_heat_pump_operation_mode

        - name: "DHW Tank Temperature (4237)"
          message: 0x4237
          id: dhw_tank_temperature_20_00_00
          unit_of_measurement: "°C"
          accuracy_decimals: 1
          filters:
            - multiply: 0.1

        - name: "Water Heater Temperature (Booster) (42E9)"
          message: 0x42E9
          id: water_heater_temperature_20_00_00
          unit_of_measurement: "°C" 
          accuracy_decimals: 1
          filters:
            - multiply: 0.1

    - address: "10.00.00" # Outdoor device address
      capabilities:
        horizontal_swing: false
        vertical_swing: false

      outdoor_temperature:
        name: "Outdoor Temperature"
        icon: "mdi:thermometer"
        device_class: temperature
        state_class: measurement
        unit_of_measurement: "°C"
        accuracy_decimals: 1
        id: outdoor_temperature_10_00_00

      outdoor_current:
        name: "Outdoor Current"
        icon: "mdi:current-ac"
        device_class: current
        state_class: measurement
        unit_of_measurement: "A"
        accuracy_decimals: 1
        id: outdoor_current_10_00_00

      power:
        name: "Outdoor Power"
        icon: "mdi:flash"
        id: power_10_00_00

      error_code:
        name: "Error Code (8235)"
        icon: "mdi:alert-circle"
        id: error_code_10_00_00
        message: 0x8235

      compressor_target_frequency:
        name: "Compressor Target Frequency (8237)"
        id: compressor_target_freq_10_00_00
        message: 0x8237
        unit_of_measurement: "Hz"

      fan_power:
        name: "Fan Power (8239)"
        id: fan_power_10_00_00
        message: 0x8239

      total_power:
        name: "Total Power (823D)"
        id: total_power_10_00_00
        message: 0x823d

      compressor_commanded_frequency:
        name: "Compressor Commanded Frequency (8236)"
        id: compressor_commanded_frequency_10_00_00
        message: 0x8236
        unit_of_measurement: "A"

      compressor_current_freq:
        name: "Compressor Current Frequency (8238)"
        id: compressor_current_freq_10_00_00
        message: 0x8238
        unit_of_measurement: "Hz"

      phase_current:
        name: "Phase Current (82DB)"
        id: phase_current_10_00_00
        message: 0x82db
        
      phase_voltage:
        name: "Phase Voltage (82DE)"
        id: phase_voltage_10_00_00
        message: 0x82de
        unit_of_measurement: "V"
        filters:
          - multiply: 0.1

      phase_power:
        name: "Phase Power (82DF)"
        id: phase_power_10_00_00
        message: 0x82df

      power_factor:
        name: "Power Factor (82E8)"
        id: power_factor_10_00_00
        message: 0x82e8
        unit_of_measurement: "pf"
        filters:
          - multiply: 0.01

      system_efficiency:
        name: "System Efficiency (82ED)"
        id: system_efficiency_10_00_00
        message: 0x82ed
        unit_of_measurement: "COP"
        accuracy_decimals: 4

      system_capacity:
        name: "System Capacity (82F6)"
        id: system_capacity_10_00_00
        message: 0x82f6
        unit_of_measurement: "kW"
        filters:
          - multiply: 0.1

      total_energy_consumption:
        name: "Total Energy Consumption (8408)"
        id: total_energy_consumption_10_00_00
        message: 0x8408
        unit_of_measurement: "kWh"
        accuracy_decimals: 6
        filters:
          - multiply: 0.001

      operation_hours:
        name: "Operation Hours (840B)"
        id: operation_hours_10_00_00
        message: 0x840b

      compressor_hours:
        name: "Compressor Hours (840C)"
        id: compressor_hours_10_00_00
        message: 0x840c

      fan_hours:
        name: "Fan Hours (841A)"
        id: fan_hours_10_00_00
        message: 0x841a

      control_wattmeter_unit:
        name: "Control Wattmeter Unit (8411)"
        id: control_wattmeter_unit_10_00_00
        message: 0x8411
        accuracy_decimals: 1

      wattmeter_accumulated:
        name: "Wattmeter Accumulated (8416)"
        id: wattmeter_accumulated_10_00_00
        message: 0x8416

      produced_energy_actual:
        name: "Produced Energy Actual (8426)"
        id: produced_energy_actual_10_00_00
        message: 0x8426

      produced_energy_total:
        name: "Produced Energy Total (8404)"
        id: produced_energy_total_10_00_00
        message: 0x8404
        unit_of_measurement: "kWh"
        accuracy_decimals: 0
        filters:
          - multiply: 0.001

      # Outdoor custom sensors
      custom_sensor:
        - name: "Outdoor Air Sensor (Airout) (8204)"
          message: 0x8204
          id: outdoor_air_sensor_10_00_00
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
            
        - name: "Defrost Mode (8031)"
          id: defrost_mode_10_00_00
          message: 0x8031
          icon: "mdi:snowflake-melt"
          unit_of_measurement: "mode"